const PORT = 5000;
const MAIN_NODE_ADDRESS = 'http://localhost:5000/';
const AVERAGE_MINING_TIME = 1000;
const STARTING_BALANCE = 500;
const REWARD_AMOUNT = 50;
const REWARD_ADDRESS = '*BLOCK REWARD*'

module.exports = {
    PORT, MAIN_NODE_ADDRESS, AVERAGE_MINING_TIME, STARTING_BALANCE, REWARD_AMOUNT, REWARD_ADDRESS
}